name: News Bot Scheduler

on:
  schedule:
    - cron: '*/30 * * * *' # هر ۳۰ دقیقه اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی هم فراهم شد

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Bot
        run: node index.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
